### ISSUE TITLE
`virt_to_folio` build error on kernel versions below 5.16

### ISSUE THREAD

**Issue by whoismissing** [kiks7/KRWX#1]
The `virt_to_folio` kernel API is only available for Linux kernel versions 5.17+.

Compiling the KRWX kernel module for commits after [a9973f819ed8c8921e32d0bcb1e9de303632f38d](https://github.com/kiks7/KRWX/commit/a9973f819ed8c8921e32d0bcb1e9de303632f38d) will result in a build error of a missing function declaration `error: implicit declaration of function 'virt_to_folio'; did you mean 'virt_to_fix'?`.

When testing against a Linux kernel version 5.15, I reverted to the KRWX commit [fbb4f201bb9b60066b458c739a08a0f8ef2560f2](https://github.com/kiks7/KRWX/commit/fbb4f201bb9b60066b458c739a08a0f8ef2560f2) in order to successfully build the kernel module.

As a quick-fix, the commit `fbb4f201bb9b60066b458c739a08a0f8ef2560f2` could be tagged as the last supported build for kernel versions before [5.16](https://elixir.bootlin.com/linux/v5.16/A/ident/virt_to_folio).

Otherwise, perhaps a kernel version check could be performed and the `virt_to_folio` feature can be disabled for older kernel builds?

**Comment by kiks7** [comment]
With commit [afc8898950d1148f0464d806530410b0c5176ff8](https://github.com/kiks7/KRWX/commit/afc8898950d1148f0464d806530410b0c5176ff8), kernels <5.16 should now be buildable without the `slab_ptr` feature. Also, the same error was with the usage of the local_lock_t, that I fixed too.

However, I used a little "trick" to check if a macro related to `virt_to_folio` is defined or not, and based on that i return -ENOTTY if the kernel doesn't support it. I think it's not the "cleanest" way, but I'm not a kernel dev and if a better solution is proposed I will go with that ! Now things should work, I will find another way to do the same job without `virt_to_folio` as soon as I have more time to dedicate.

I'm also going to plan a code cleaning task to make it easier if someone want to do some fixes here and here.

Thank you again for the issue!
Alessandro
